replicasCount: 1
appPort: 5000

image:
  registry: joaofmds/restapi-flask
  tag: latest

environmentVariables:
  - name: FLASK_ENV
    value: development

environmentVariablesFrom:
  - secretRef:
      name: mongodbcredentials

livenessProbe:
  httpGet:
    path: /health
    port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: 5000

ingress:
  enabled: true

mongodb:
  database: AgAPoovVW4+yT8ZEo0mJjARYaxBTTzqutO9N5+ihHVyiTcijV1/7o1y4OjwlndHyKnEDInMrUgy1uMwSqLYT+EDxjBMar9pu0Sap/+3K+RXwxSKQ7b6j90BnpPwSUKCtJ83d0fg1jijPeKUjpEM633MpcKYOpODk+ZQMWEWC//ZBoXh+O6WvNZqXZHfkOMErpWDR/30w24U9qsiF9KKeR9r7wnKB+Gxp9N+3LUmAvYlYSS1G1lEdG03n7/VQyIdpCqgDNTs+TiLhYT8YDf9HfKDg34ReNIrhpfexsy879/lusEWkFW2sylIS4AoHtn5MM+WIikhRj2KQfjwOe3IQOoWwksl38IMkCh4c4tff8VJpJPd48+PCRMImE+lqa7pmF27zekAWlfEV2ghVmdmZdvKuDH7K+7RCTtuKOSHTbU41idI1KyNlkoDLAb/a/n2hLDLymQ3rhRrJ+Xr0FWAnhCUNl/Na7qpx4Q9XZVerqthawqn2u0E7FmABW5raxNscM+hG5OexBWxSF2SLuQDM9U51kq3hK5gsHuohbSUVJVm9cBjUDsIPekNxz5eD9h/u9CX2eKfsRzpG2K+ZpAZtgqoPbQebp7qKBaZonLVIQZXM2LnS44C5E88nhGCjkbnzVy7V7qWBksxD0E0MH/iJoLID9cx2jDI9H5NL0NYgRe4Es0zkr8C0CbNdBaDK0Yd8GO/k5DcAhg==
  host: AgAE/0drMFpAPf3t1zckG3++6GnAS+/vhWrwRq4K2p+Gyv6SEOhX/WnwfdZTBmwNdf9TfsejSGZC2HPnG6I6aj4bCMYqS8SrogLPlxz5Hy6QbZJtsW+RXS4GfofnzOZIW6YXDq+K1Ow+nMPI1/RfXjftlvL53Vkphw0GOwFLEnp6Oz9ZfIBfgqZs9WUyqHK1Ky0UTgwR8M6RQ9kloWLbsUs325pNMSR8TSRdB0/kqPPZW8g78c7um58XhnR7g7G8KmjBjJJO5M9GIahG5xCVSYQN1pTUwQa1p4SqY4OUeyBj7MqyJlUlMBNpKh1bnZpdVJoZY3TZzy1vT20HkDF0eTNeLebRORVJsk9ZriRkah1ci6q8+EFnIuRATYOpkFsz2HU9Rx5x0xkoptAQiO4wkbPYLe8eh+rUOg9n8HDULc3FFF/BUxzCtlj4O1MhmxQcOG8FgCUroHMxS8LdSPvgl70Q+F34FwM4qb4OMeoVfwQjdgOQf2aGx3yjnytp3CzLlGSbvtRxdHW8eY1EwsSds/RC57PD+ZLlD8aaIOM8IqSnSZxU/CUp+5rvO6qndtezyuchFwOOg0HHEr3naQp85LXgdvx39l6kFwCcJWRauwiwP1AVVEJg3Fnvwata0L4et54KA5FtQ2sIy+IW+7loCEEUZSDo2nj5cS0QRhPPIYMMPYDEyu8C5DO2YjX54eMFduMFPQnZGYsjlIC0RA==
  password: AgBLa8zDfFdUVmpWs32gvjVmkyPjifd2nXaCFGsaZNIhhyX8UCHpXHV9SIvtJnxXctSAcuzAZfgPjmz2Ttv0Vy6/M/OAJyTcPc7OHnxaftZPYbxvh58BfHIrlBtTuBY73kMYwLf+P/UiPXp/SECIXgfdUmpp/rHtyag4I4/hquoH48zN8xr8HtgVLjLhpER2Y3uwUPz+b0Wul8zAPejpV8WxFGQY50NCO/PjpSOzP0etDFtpyHbpneAWnRL09jZB89ArBbnusRfz8tHrGNYEqqXrhcJeOacHE6a/5cwSpGLoNrmSyJtBOuPOy9m+uID/npQYTDv1Mjz7utrWe6MPOjxqFd2Vgo/cDlE2jQS2EriuEJIFlgLjCFz7DLQztM94myf45GtReMUWKdKza5ETxMEJ8DsXzVH2YfiS4dk2kTxeaMQy6PeSIs83DUV01HnNoKQgwqgnsNZmB9NpJ/a/z/ZW25nULtqFS5MSx5gVh5H0mHJU2WYWvS6Rd4wS5U9CI8Lf94YWmLFQWMz8klmxfKtUrNNKJ8Y8VjJ/4dDYvzr3tBaVuT1tmHHFg57C5eb/ga0g7jVmIrgta5b8YUcBNDWo/Nb7QkvD5HcjHOm9mwtRw/ES4SxU6aNFakV49Rm/bPaHJQQ8f8GJBPLXx6nVet42nidpzNGlMToFYubOdD8nWp8UiYwU4xGP6Y4eEtSzAtiX2NThjXdYrDwfUTc=
  user: AgB5m6gMcxQR0P+us82jRWjBwpN1kJamYHhGCuIbKFcT1xb9KVGRhWliZhcTWN/WZvVkto8A7nL5ykCRPtMzLAF0a8qOfVCwy7dCufAVjjrDCPGMw7GYAUV55VidOp3xm7i79Qg039V1j70lPVwx8HjNd10WwzTUHR0hwqOxHoDcfGQbURskfJZpQSWTMSweIS++FnHuxEzhcvIAeC7lBRJ8UTvTvRJ5baXsJ/Fu+SO5wgTbzk9q8shoZZ2tplsIrrYdG0GRCX6nbbc/frNBuwJqeksvOmBqzLLMahwqcZ2pVm6enkcwvecVLm5IaSMfwqSQlFrnOy8zY5r6MJNrWNpAtcq1EJxRd4OSuCkWUBQ55988SKprQnLajFsu1g6WhXfjgemyex04q/0jXl3+y9nnAyp/+fzbyFl8PoZAZFY9lsrKf4L/3igb/Ke6a3ve2O14gyn3/n0Uw6rPqyCIaEW6+7xtBbdn1GmhvGUqHWFGM2N5vz44jQI7LUBDl+UtV4HEHnonKj8egT5Xh+trQULbb6PDSCMETX61Ph+ZSBLnMICUTaiHoDyfrkzZSGcL4gFIdspv16puVANjbFlQjXiMwPxWy+6cFtEeo3YfVmqMkrUwKDvdnjrMCs3FvAaVonOknhVMg8miiFuz7wmfDwxfx9Wslc45qPVKBoELokYqBnmYP2vFcqidbpcycoYZgqhN3T1I4u0Z
