---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodbcredentials
  namespace: default
spec:
  encryptedData:
    MONGODB_DB: {{ .Values.mongodb.database }}
    MONGODB_HOST: {{ .Values.mongodb.host }}
    MONGODB_PASSWORD: {{ .Values.mongodb.password }}
    MONGODB_USER: {{ .Values.mongodb.user }}
  template:
    metadata:
      creationTimestamp: null
      name: mongodbcredentials
      namespace: default
